[package]
name = "sketch"
version = "0.1.0"
edition = "2021"

[features]
default = ["paste"]
paste = ["crossterm/bracketed-paste"]

[dependencies.crossterm]
version = "0.28.1"
default-features = false
features = [
    "events",
    "windows",
]
